### ISSUE TITLE
i can not use preview

### ISSUE THREAD

**Issue by khotaonickvai** [BadRyuner/dnspy.Cpp2IL#1]
i downloaded lastest dnspyEx but i could find out extensions forlder. I have created the folder and paste all .dll file in preview .7z but i got nothings when open dnspy and import game assembly.

**Comment by BadRyuner** [comment]
I think this way it should be clearer how to install the plugin and how it works.
[howtoinstall.webm](https://github.com/BadRyuner/dnspy.Cpp2IL/assets/54708336/97741219-d06c-4eae-8575-60413cd47b99)

**Comment by wangjunxiao0207** [comment]
I also can not use preview.
it loaded the extension, but dnSpy can't decompile apk file.
![image](https://github.com/user-attachments/assets/89f5bf35-3d8f-4be0-8705-b52e71444e5d)
![Uploading image.png…]()

**Comment by BadRyuner** [comment]
Try generating dummy dlls for your apk using this version of cpp2il: https://github.com/SamboyCoding/Cpp2IL/releases/tag/2022.1.0-pre-release.17
If it gives an error, it is a problem in the cpp2il library. If everything is OK, then I'm screwed somewhere. I don't know where exactly, because I didn't add the error output.
